package uk.co.n3tw0rk.oaigatewayrelay.events.miscellaneous;

/**
 * 
 * @author M00SEMARKTWO

STATION MESSAGE RECORDING – SMR
NOTE: This event is available only in protocol versions 09.00 and later.
ALSO: The node to be monitored must support OAI Protocol V09.00 or later and if a CT Gateway
is used it must be V4.2xx or later.
USE: Occurs whenever SMDR is generated by call processing.
The application must enable a system monitor on the node (or nodes) with the correct filter
mask enabled. A new system filter bit has been added and can be supplied as part of the _MS,
_MA, or _CE commands.
MONITOR TYPE: System
SYNTAX: SMR,<Resync_Code>,<Mon_Cross_Ref_ID>,<Node_Number>,<SMDR_INFO><CR><LF>
Where:
• Node_Number: Indicates the node number that is reporting the SMDR information.
This is the node number from which the SMDR information is being sent. This might
not be the node where the SMDR data originally came from because nodes can route
the SMDR data to another node for reporting. In addition, due to limitations in previous
versions of Axxess, the node number may be the last node number to receive the message
if any of the nodes are not Axxess V09.00 or later or Inter-Tel 5000 V01.00.
To illustrate the differences in the SMR event outcome, consider the following example.
If an SMDR event is created on Node 4 (Inter-Tel 5000 V01.00), and it is routed to Node
3 (Axxess V08.20), and then routed to Node 1, the SMR event will report Node 3 and
not Node 4.
If the SMR event is initiated by Node 3, and then routed to Node 4 and then to Node 1
or directly to Node 1, the SMR event will report Node 3.
The way to guarantee the correct node number value in the SMR event is to either have
each node directly connected to the reporting node (which is easy if all the nodes are
connected via TCP/IP) or upgrade all the nodes to Axxess V09.00 or later or Inter-Tel
5000 V01.00.
• SMDR_INFO: Specifies a || delimited field that contains the data normally sent out of
the SMDR port.
_MS, _MA, _QE,
_CE COMMAND
IMPACT:
To enable SMR events, you can enable the system filtering using _MS, _MA, _QE and _CE
commands. By default, the SMR event is disabled. The QE command returns the new bit in the
confirmation.
EXAMPLES: Start system monitoring all system events.
_MS,<InvokeID>,1000,11
001,CF,_MS,<InvokeID>,0,<Mon_Cross_Ref_ID>,1,,S:00FD
Start system monitoring all system events.
_MS,<InvokeID>,1000,11
001,CF,_MS,<InvokeID>,0,<Mon_Cross_Ref_ID>,1,,S:00FD
Monitor all nodes with default filter settings.
_MS,1,,11
_MS,1,,11,S:0000
Start system monitoring all system events.
_MA,<InvokeID>,1000,11,S:00FD
001,CF,_MA,<InvokeID>,0,1,11,1, ,S:00FD
Disable all events on system monitor 100.
_CE,<InvokeID>,100,S:0
001,CF,_CE,<InvokeID>,0,S:0
Enable all events on the system monitor, 101.
_CE,<InvokeID>,101,S:00FD
001,CF,_CE,<InvokeID>,0,S:00FD
Query Event filter on system monitor, 101.
_QE,<InvokeID>,101
001,CF,_QE,<InvokeID>,0,S:00FD
RESYNC REQUEST
– RR IMPACT:
The SMR event will not be generated on a resync request.
MULTIPLE NODES
IMPACT:
System events are not "filterable" on a node basis. So if SMDR data is not needed from a particular
node, that node should not send its SMDR data to the node reporting SMDR via OAI.
TROUBLESHOOTING
TIPS: SYMPTOM PROBABLE CAUSE RESOLUTION
Unable to set the system
event to enable the SMDR
event.
Either the node is not a
V09.00 protocol or an incorrect
command to enable the
monitor is being used.
Verify that the node is the
correct version; in the event
of a CT Gateway, all the
nodes must be the correct
version. Also verify that the
format of the OAI command
to enable the monitor is correct.
The monitor must be a
system monitor and the
event mask bit 1 must be
enabled.
Unable to get SMR events. SMDR event reporting is not
enabled on the node. Also
the node may not be the
proper version of Axxess/
Inter-Tel 5000. Also quite
possible that the SMDR is
being routed from the node
to another node. In this
event the SMR event would
need to be obtained from
that node. Additionally, if
using a CT Gateway, the CT
Gateway version needs to
be 4.2xx or later. When a CT
Gateway is used, the SMR
event may not be enabled
when setting up system
monitors on all the nodes at
once if any of the nodes is
not using protocol version
09.00 or later.
Verify that SMDR reporting is
properly set up on the node.
Verify that the system monitor
on the node(s) reporting
SMDR is enabled and that
bit 1 is enabled for the monitor.
Also be sure that if
using a CT Gateway that it is
version 4.200 or later. Also
when using a CT Gateway,
all nodes need to be protocol
version 09.00 or later for the
application.
 */
public class StationMessageRecording {

}
